spring.application.name=Autonation-USA


spring.datasource.username=root
spring.datasource.password=Abhi890@
server.port=6666

spring.datasource.url=jdbc:mysql://localhost:3306/AutoNation
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.security.user.name=abhi
spring.security.user.password=1234


